# Travis CI config file

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pipenv
  - pip install pytest-cov
  - pip install codecov

script:
  pytest --cov=nhs_number --cov-report=term -v

after_success:
  codecov

deploy:
  - provider: pypi
    user: $TEST_PYPI_USER
    password: $TEST_PYPI_PASS
    server: https://test.pypi.org/legacy/
    distributions: "sdist bdist_wheel"
    on:
      branch: staging
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
  #
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      branch: main
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
