# Travis CI config file

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pipenv
  - pip install pytest-cov
  - pip install codecov

script:
  pytest --cov=nhs_number --cov-report=term -v

after_success:
  codecov
