# netlify.toml
# required for Netlify deploy of the docs site

[build]
  command = "pip3 install -q poetry && poetry config virtualenvs.in-project true && poetry install -v && mkdocs build -d site"
  publish = "site"
